### PR TITLE
Add stdint.h

### PR DESCRIPTION
**Pull request by TaoL33T**
stdint contains any alternative variables (uint8_t, uint32_t, etc.)

### CODE REVIEW

**Comment by TaoL33T** [comment]
Looks like I don't know how to use github, so there is also another update. A better checking for so called "signatures".

**Comment by animetosho** [comment]
Thanks a lot for this PR!

It looks like you ran a code formatter on this, which makes the diff really big. Could I ask you to undo the formatting so that it only shows the actual changes?  
Alternatively, I can just copy over the changes myself, if you prefer that.

**Comment by TaoL33T** [comment]
I don't really know how to use any of github features. You can copy over the changes, I don't mind at all.

**Comment by animetosho** [comment]
Okay, I've committed the changes.  
Thanks!

**Pull request closed without merging**
